language: node_js
node_js:
  - "8"

before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global push.default simple
  - git remote set-url origin https://${GH_TOKEN}@github.com/Multicaja/api.git

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - npm install -g spectacle-docs
  - npm install -g redoc-cli
  - npm install -g base64-js
  - npm install -g builtin-status-codes
  - npm install -g ieee754
  - npm install -g to-arraybuffer
  - npm install -g xtend

script:
  # Get proper branch name based on http://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  # All variables ready - run the test script
  - bash api-spec_validation_test.sh
  # Build docs pages
  - spectacle --target-dir docs --target-file api-users.html api-users.yml
  - redoc-cli bundle -o api-users-redoc.html api-users.yml
  - spectacle --target-dir docs-prepaid --target-file api-prepaid.html api-prepaid.yml
  - redoc-cli bundle -o api-prepaid-redoc.html api-prepaid.yml
  - spectacle --target-dir docs-paypal --target-file api-paypal.html api-paypal.yml

  - spectacle --target-dir docs-recharges --target-file api-recharges.html api-recharges.yml
  - redoc-cli bundle -o api-recharges-redoc.html api-recharges.yml
  - spectacle --target-dir docs-card-payments --target-file api-card-payments.html api-card-payments.yml
  - redoc-cli bundle -o api-card-payments-redoc.html api-card-payments.yml
  - spectacle --target-dir docs-api-prepaid-2 --target-file api-prepaid-2.html api-prepaid-2.yml
  - redoc-cli bundle -o api-prepaid-2-redoc.html api-prepaid-2.yml

  - mv docs-prepaid/api-prepaid.html docs/
  - mv api-prepaid-redoc.html docs/
  - mv docs-paypal/api-paypal.html docs/

  - mv docs-recharges/api-recharges.html docs/
  - mv api-recharges-redoc.html docs/
  - mv docs-card-payments/api-card-payments.html docs/
  - mv api-card-payments-redoc.html docs/
  - mv docs-api-prepaid-2/api-prepaid-2.html docs/
  - mv api-prepaid-2-redoc.html docs/

  - cp README.md docs/
 
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  verbose: true
  on:
    branch: master
