language: bash

before_install:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config --global push.default simple
  - git remote set-url origin https://${GH_TOKEN}@github.com/Multicaja/api.git

before_script:
  - curl -L "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/shunit2/shunit2-2.1.6.tgz" | tar zx
  - npm install -g spectacle-docs

script:
  # Get proper branch name based on http://graysonkoonce.com/getting-the-current-branch-name-during-a-pull-request-in-travis-ci/
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
  # All variables ready - run the test script
  - bash api-spec_validation_test.sh
  # Build docs pages
  - spectacle --target-dir docs --target-file api-users.html api-users.yml
  - spectacle --target-dir docs-prepaid --target-file api-prepaid.html api-prepaid.yml
  - spectacle --target-dir docs-paypal --target-file api-paypal.html api-paypal.yml
  - spectacle --target-dir docs-recharges --target-file api-recharges.html api-recharges.yml
  - spectacle --target-dir docs-bdp --target-file api-bdp.html api-bdp.yml
  - spectacle --target-dir docs-card-payments --target-file api-card-payments.html api-card-payments.yml
  - mv docs-prepaid/api-prepaid.html docs/
  - mv docs-paypal/api-paypal.html docs/
  - mv docs-recharges/api-recharges.html docs/
  - mv docs-bdp/api-bdp.html docs/
  - mv docs-acquirement/api-card-payments.html docs/
  - cp README.md docs/
 
deploy:
  edge:
    branch: v1.8.47 # https://github.com/travis-ci/travis-ci/issues/9312
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  local-dir: docs
  verbose: true
